### ISSUE TITLE
Can this be used as a standalone db?

### ISSUE THREAD

**Issue by durgaswaroop** [yahoo/HaloDB#1]
Hi, The description says that HaloDB can be embedded into an application. I was wondering if there is a way to set it up as a standalone DB and connect to it from a remote application. Is that possible?

**Comment by ngrigoriev** [comment]
I do not see why not, but you will have to put some sort of layer around it, an API. Maybe the simplest way would be something with RPC (gRPC etc). But you will have to manage the concurrency, it seems that the writes must be protected by the application, i.e. in this case by your API. I would say that the DB server that cannot do concurrent writes is relatively useless for something real.

**Comment by durgaswaroop** [comment]
> I would say that the DB server that cannot do concurrent writes is relatively useless for something real
That is not really an issue for my application.  
Still, what is the current behavior in the case when two simultaneous writes are called?

**Comment by ngrigoriev** [comment]
From the README:

```
            // add the key-value pair to the database.
            // HaloDB doesn't support cocurrent writes.
            // This is expected to be enforced by the calling application.
            db.put(key1, value1);
            db.put(key2, value2);
```

If someone says that the concurrent operation is not supported, I usually believe that ;)

**Comment by amannaly** [comment]
@durgaswaroop 
The distributed database which is currently using HaloDB use Kafka as a kind of distributed write-ahead log. Clients write to Kafka and there is a thread in the database which will read from Kafka and then write to HaloDB. Therefore, all writes to HaloDB are from a single thread. Since I was tying to first optimize HaloDB for this particular workload I haven't optimized it for concurrent writes yet. This is a task for the future. 

You can issue concurrent writes to HaloDB, it doesn't affect the correctness of data, but concurrent writes to HaloDB will block till the write request currently in progress completes. 
Also note that writes _don't_ block reads. 

I have updated the documentation as it was misleading. 

For an IO bound workload writes to HaloDB are fast, therefore, this shouldn't affect performance much. Of course if you have tens or hundreds of threads doing concurrent writes there will probably be a significant synchronization overhead. 

I plan to use finer grained locking for writes, but that is for another day. 

Thank you for your interest in contributing to HaloDB, contributions are welcome. There is a list of TODO items. I will create issues  with description for them. Please watch this repository.
